# Here is a sample command to run this playbook:
# ansible-playbook provision-workstation.yml  --ask-sudo-pass

# Fix the firefox input form backgrounds being grey on white
# Put this in ~/.mozilla/firefox/<profile_dir>/chrome/userContent.css
# input:not(.urlbar-input):not(.textbox-input):not(.form-control):not([type='checkbox']):not([type='radio']), textarea, select {
#     -moz-appearance: none !important;
#     background-color: white;
#     color: black;
# }

# #downloads-indicator-counter {
#     color: white;
# }
#
#
# Stop the stupid printer notifications:
# Edit /etc/cups-browsed.conf, changing the BrowseRemoteProtocols CUPS dnssd line to BrowseRemoteProtocols none
# https://askubuntu.com/questions/918462/ubuntu-17-04-printer-added-notifications-under-gnome

# TODO:
# Install Standard Notes
# Install Etcher
# Install Hub
# Install JIRA (Netflix)
# Check if we need alternate tab in 18.04, or can assign the keyboard shortcut
# Set gnome-terminal profile preferences
# Run sensors detect if not already done
# Run powertop calibration if not already done
# Run powertop optimization if not already done
# PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;34m\]\W\[\033[00m\]\$ "
# todo: change keyboard shortcut to switch windows (not switch applications)
# remove thunderbird,
# remove Amazon from the software center
# https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

# gsettings set org.gnome.shell.extensions.dash-to-dock autohide false
# gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false
# gsettings set org.gnome.shell.extensions.dash-to-dock intellihide false


# gsettings set org.gnome.shell enable-hot-corners true
# gsettings set org.gnome.shell.app-switcher current-workspace-only true
# gsettings set org.gnome.gedit.plugins active-plugins "['modelines', 'spell', 'drawspaces', 'codecomment', 'docinfo']"
# gsettings set org.gnome.gedit.preferences.editor auto-indent true
# gsettings set org.gnome.gedit.preferences.editor bracket-matching true
# gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
# gsettings set org.gnome.gedit.preferences.editor display-right-margin true
# gsettings set org.gnome.gedit.preferences.editor highlight-current-line true
# gsettings set org.gnome.gedit.preferences.editor insert-spaces true
# gsettings set org.gnome.gedit.preferences.editor right-margin-position 120
# gsettings set org.gnome.gedit.preferences.editor scheme oblivion
# gsettings set org.gnome.gedit.preferences.editor tabs-size 4
# gsettings set org.gnome.desktop.interface clock-show-date true
# gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark
# gsettings set org.gnome.desktop.interface icon-theme Humanity-Dark
# gsettings set org.gnome.desktop.interface show-battery-percentage true
# gsettings set org.gnome.desktop.calendar show-weekdate true
# gsettings set org.gnome.desktop.privacy remember-recent-files false
# gsettings set org.gnome.desktop.privacy remove-old-trash-files true
# gsettings set org.gnome.eog.ui disable-close-confirmation true
# gsettings set org.gnome.meld highlight-current-line true
# gsettings set org.gnome.meld highlight-syntax true
# gsettings set org.gnome.mutter attach-modal-dialogs false
# gsettings set org.gnome.mutter dynamic-workspaces false
# gsettings set org.gnome.mutter workspaces-only-on-primary false
# gsettings set org.gnome.nautilus.preferences confirm-trash false
# gsettings set org.gnome.online-accounts whitelisted-providers "[]"
# gsettings set org.gnome.shell enable-hot-corners true




# Atom notes:
# Don't enable the autosave extension, since I only want to save when I leave Atom, not every tab change


- hosts: localhost
  gather_facts: False
  become: no
  tasks:
    - name: Add the set-title bash function
      blockinfile:
        path: ~/.bashrc
        block: |
            # Taken from http://unix.stackexchange.com/questions/177572/how-to-rename-terminal-tab-title-in-gnome-terminal
            function set-title() {
                if [[ -z "$ORIG" ]]; then
                    ORIG=$PS1
                fi
                TITLE="\[\e]2;$@\a\]"
                PS1=${ORIG}${TITLE}
            }

    - name: Add lines into .bashrc
      lineinfile:
        path: ~/.bashrc
        line: "{{ item }}"
      with_items:
        - export PATH=$PATH:/opt/bin
        - export EDITOR=/bin/nano

        # Clip to clipboard
        - alias clip="xclip -selection c"

        # Useful tool to get 1 line names of PRs.
        - alias gitpoky="git --no-pager log --first-parent --format=\"%ad %H %s\" --date=short --reverse $@ | tail -n 50"
        - alias gitupdate="git checkout master && git pull --rebase upstream master"

        # Set keyboard delays (lower them!)
        - xset r rate 150 60

    - name: Add lines to .nanorc
      lineinfile:
        path: ~/.nanorc
        create: yes
        line: set autoindent

- hosts: localhost
  gather_facts: False
  become: yes
  vars:
    user: "{{ lookup('env','USER') }}"
  tasks:
    - name: Create folder for custom programs
      file:
        path: /opt/
        state: directory

    - name: Copy custom programs
      copy:
        src: bin
        dest: /opt/

    - name: Make custom programs executable
      file:
        path: /opt/bin/
        mode: 0755
        recurse: yes

    - name: add the Atom package repo signing key
      shell: wget -qO- https://packagecloud.io/AtomEditor/atom/gpgkey | apt-key add -

    - name: add the Atom deb repository
      shell: echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list

    - name: Update cache (with no fail because on old computer some things didn't download, etc.)
      apt:
        update_cache: yes
      failed_when: false

    - name: Update computer
      apt:
        upgrade: dist

    - name: Install Packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: no
      with_items:
        - atom
        - chrome-gnome-shell
        - chromium-browser
        - conky
        - dconf-editor
        - docker.io
        - gedit-plugins
        - giggle
        - gimp
        - git
        - gitg
        - gnome-tweak-tool
        - gnuplot
        - htop
        - inkscape
        - iotop
        - isort
        - inotify-tools
        - lm-sensors
        - meld
        - meshlab
        - nautilus-image-converter
        - nautilus-wipe
        - nmap
        - parallel
        - picocom
        - poedit
        - postgresql-client
        - powertop
        - tftp
        - tmux
        - traceroute
        - tree
        - ttf-mscorefonts-installer
        - vagrant
        - virtualbox
        - vlc
        - wireshark
        - whois
        - xclip

        # Install pip things
        - python3-pip
        - python3-dev
        - build-essential

        # Node things
        - nodejs
        - npm
        - build-essential

        # For gnome shell system monitor applet: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet
        - gir1.2-gtop-2.0
        - gir1.2-networkmanager-1.0
        - gir1.2-clutter-1.0

        # For atom editor things
        - shellcheck

    - name: Update pip
      pip:
        name: pip
        state: latest
        executable: pip3

    - name: Install pip packages
      pip:
        name: "{{ item }}"
        state: latest
        executable: pip3
      with_items:
        - ansible-lint
        - autoflake
        - autopep8
        - awscli
        - flake8
        - jupyter
        - matplotlib
        - mock
        - mypy
        - psycopg2
        - pydocstyle
        - pyinotify
        - pyserial
        - pytz

    - name: Install Nodejs packages
      npm:
        name: "{{ item }}"
        state: latest
        global: yes
      with_items:
        - eslint
        - jshint

    - name: Adding existing user "{{ user }}" to groups
      user:
        name: "{{ user }}"
        groups: "{{ item }}"
        append: yes
      with_items:
        - dialout
        - docker

    # https://unix.stackexchange.com/a/13757
    - name: Increase inotify watches
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^fs.inotify.max_user_watches='
        line: fs.inotify.max_user_watches=1250000

- hosts: localhost
  gather_facts: False
  become: no
  tasks:
    - name: Set up git config settings
      shell: "{{ item }}"
      with_items:
        - git config --global submodule.recurse true
        - git config --global push.followTags true
        - git config --global user.name "Cody Lewis"
        # git config --global user.email ""

    - debug:
        msg: "Please run git config --global user.email with the prefered email."

    - name: Provide shell extension URLs to install
      debug:
        msg: "{{ item }}"
      with_items:
        - https://extensions.gnome.org/extension/120/system-monitor/
        - https://extensions.gnome.org/extension/15/alternatetab/
        - https://extensions.gnome.org/extension/307/dash-to-dock/
        - https://extensions.gnome.org/extension/906/sound-output-device-chooser/
        - https://extensions.gnome.org/extension/21/workspace-indicator/
        - https://extensions.gnome.org/extension/28/gtile/
        - https://extensions.gnome.org/extension/3/bottom-panel/
