# Here is a sample command to run this playbook:
# ansible-playbook --ask-become-pass provision-workstation.yml
#
#
# Stop the stupid printer notifications:
# Edit /etc/cups-browsed.conf, changing the BrowseRemoteProtocols CUPS dnssd line to BrowseRemoteProtocols none
# https://askubuntu.com/questions/918462/ubuntu-17-04-printer-added-notifications-under-gnome

# TODO:
# Run sensors detect if not already done
# Run powertop calibration if not already done
# Run powertop optimization if not already done
# todo: change keyboard shortcut to switch windows (not switch applications)


# Atom notes:
# Don't enable the autosave extension, since I only want to save when I leave Atom, not every tab change



# 20.04
# Disable tracker miner
#  https://www.linuxuprising.com/2019/07/how-to-completely-disable-tracker.html
#  https://askubuntu.com/questions/346211/tracker-store-and-tracker-miner-fs-eating-up-my-cpu-on-every-startup
#
# Install Display Link Driver
#
# APM install sync-settings
#
#
# Chrome also installs key and sources.list.d??
# Inkscape 1.0: https://inkscape.org/release/inkscape-1.0/gnulinux/ubuntu/ppa/dl/

- hosts: localhost
  gather_facts: False
  become: no
  tasks:
    - name: Add the set-title bash function
      blockinfile:
        path: ~/.bashrc
        block: |
            # Taken from http://unix.stackexchange.com/questions/177572/how-to-rename-terminal-tab-title-in-gnome-terminal
            function set-title() {
                if [[ -z "$ORIG" ]]; then
                    ORIG=$PS1
                fi
                TITLE="\[\e]2;$@\a\]"
                PS1=${ORIG}${TITLE}
            }

    - name: Add lines into .bashrc
      lineinfile:
        path: ~/.bashrc
        line: "{{ item }}"
      with_items:
        - export PATH=$PATH:/opt/bin
        - export EDITOR=/bin/nano

        # Clip to clipboard
        - alias clip="xclip -selection c"

        # Useful tool to get 1 line names of PRs.
        - alias gitpoky="git --no-pager log --first-parent --format=\"# %ad %H %s\" --date=short --reverse $@ | tail -n 50"
        - alias gitupdate="git checkout master && git pull --rebase upstream master"

        # Set keyboard delays (lower them!)
        # - xset r rate 150 60

    - name: Add lines to .nanorc
      lineinfile:
        path: ~/.nanorc
        create: yes
        line: set autoindent

- hosts: localhost
  gather_facts: False
  become: yes
  vars:
    user: "{{ lookup('env','USER') }}"
  tasks:
    - name: Create folder for custom programs
      file:
        path: /opt/
        state: directory

    - name: Copy custom programs
      copy:
        src: bin
        dest: /opt/

    - name: Make custom programs executable
      file:
        path: /opt/bin/
        mode: 0755
        recurse: yes

    - name: add the Atom package repo signing key
      apt_key:
        url: https://packagecloud.io/AtomEditor/atom/gpgkey
        state: present
    - name: add the Atom deb repository
      apt_repository:
        repo: "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main"
        state: present

    - name: Add Chrome repo signing key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present
    - name: Add Chrome repository
      apt_repository:
        repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        state: present

    - name: Update cache
      apt:
        update_cache: yes

    - name: Update computer
      apt:
        upgrade: dist

    - name: Remove Packages
      apt:
        name: "{{ item }}"
        state: absent
        update_cache: no
      loop:
        - thunderbird

    - name: Install Packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: no
      loop:
        - atom
        - chrome-gnome-shell
        - conky
        - dconf-editor
        - docker.io
        - gcc
        - gedit-plugins
        - giggle
        - gimp
        - git
        - gitg
        - gnome-tweak-tool
        - gnuplot
        - google-chrome-stable
        - htop
        - inkscape
        - inotify-tools
        - iotop
        - isort
        - libpq-dev
        - lm-sensors
        - meld
        - meshlab
        - nautilus-image-converter
        - nautilus-wipe
        - nmap
        - parallel
        - picocom
        - poedit
        - postgresql-client
        - powertop
        - tftp
        - tmux
        - traceroute
        - tree
        - ttf-mscorefonts-installer
        - vagrant
        - virtualbox
        - vlc
        - whois
        - wireshark
        - xclip

        # Install pip things
        - python3-pip
        - python3-dev
        - build-essential

        # Node things
        - nodejs
        - npm
        - build-essential

        # For gnome shell system monitor applet: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet
        - gir1.2-gtop-2.0
        - gir1.2-nm-1.0
        - gir1.2-clutter-1.0

        # For atom editor things
        - shellcheck

    - name: Update pip
      pip:
        name: pip
        state: latest
        executable: pip3

    - name: Install pip packages
      pip:
        name: "{{ item }}"
        state: latest
        executable: pip3
      loop:
        - ansible-lint
        - autoflake
        - autopep8
        - awscli
        - flake8
        - jupyter
        - matplotlib
        - mock
        - mypy
        - psycopg2
        - pydocstyle
        - pyinotify
        - pyserial
        - pytz
        - psutil

    - name: Install Nodejs packages
      npm:
        name: "{{ item }}"
        state: latest
        global: yes
      loop:
        - eslint
        - jshint

    - name: Adding existing user "{{ user }}" to groups
      user:
        name: "{{ user }}"
        groups: "{{ item }}"
        append: yes
      loop:
        - dialout
        - docker

    # https://unix.stackexchange.com/a/13757
    - name: Increase inotify watches
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^fs.inotify.max_user_watches='
        line: fs.inotify.max_user_watches=1250000

    - name: Check if snap is installed
      command: "snap list"
      register: snap_check
      changed_when: false
      failed_when: false
    - name: Remove snaps
      snap:
        name: "{{ item }}"
        state: absent
      loop:
        # Order matters here.
        - "chromium"
        - "gnome-3-34-1804"
        - "gtk-common-themes"
        - "snap-store"
        - "core18"
        - "snapd"
      when: snap_check.rc == 0
    - name: Remove the snap package
      apt:
         name: "snapd"
         state: absent
         purge: yes

    - name: Download hub
      get_url:
        url: https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz
        checksum: "sha256:74d95fdfb3c78c8af4e2025b04b916ad905ab99a361778500d58269847c7922d"
        dest: /tmp/
    - name: Extract hub
      unarchive:
        src: /tmp/hub-linux-amd64-2.14.2.tgz
        dest: /tmp/
        remote_src: yes
        mode: 0755
        extra_opts:
          - "hub-linux-amd64-2.14.2/bin/hub"
    - name: Install hub
      command: mv /tmp/hub-linux-amd64-2.14.2/bin/hub /opt/bin/hub-2.14.2
    - name: Set hub sym link
      file:
        src: '/opt/bin/hub-2.14.2'
        dest: '/opt/bin/hub'
        state: link


    - name: Download and install Standard Notes
      get_url:
        url: https://github.com/standardnotes/desktop/releases/download/v3.4.1/Standard-Notes-3.4.1.AppImage
        checksum: "sha256:b1be6f2c99b02d492ed1d2ba4644a83e9caa67d8cef42adb098cf5a81b2cadae"
        dest: /opt/bin/Standard-Notes-3.4.1.AppImage
        mode: 0755
    - name: Set Standard Notes sym link
      file:
        src: '/opt/bin/Standard-Notes-3.4.1.AppImage'
        dest: '/opt/bin/Standard-Notes'
        state: link


    - name: Download and install jira
      get_url:
        url: https://github.com/go-jira/jira/releases/download/v1.0.23/jira-linux-amd64
        checksum: "sha256:e2550f69ed5471bf4699554ff72b4bb41445266ae3a2c02a4594cd0557dd1f2a"
        dest: /opt/bin/jira-v1.0.23
        mode: 0755
    - name: Set JIRA sym link
      file:
        src: '/opt/bin/jira-v1.0.23'
        dest: '/opt/bin/jira'
        state: link


- hosts: localhost
  gather_facts: False
  become: no
  tasks:
    - name: Set up git config settings
      shell: "{{ item }}"
      with_items:
        - git config --global submodule.recurse true
        - git config --global push.followTags true
        - git config --global user.name "Cody Lewis"
        # git config --global user.email ""

    - debug:
        msg: "Please run git config --global user.email with the prefered email."

    - name: Provide shell extension URLs to install
      debug:
        msg: "{{ item }}"
      with_items:
        - https://extensions.gnome.org/extension/120/system-monitor/
        - https://extensions.gnome.org/extension/906/sound-output-device-chooser/
        - https://extensions.gnome.org/extension/21/workspace-indicator/
        - https://extensions.gnome.org/extension/28/gtile/

    - name: Pause until extensions are installed
      pause:
        prompt: "Please ensure that the Gnome extensions are installed"

    # Use the gsettings command because the Ansible dconf role seems to put some values into a "shadow" register,
    # rather than the actual key that the dconf GUI sees. It might be tied to the handling of strings, etc.
    - name: Set gsettings values
      shell: "{{ item }}"
      loop:
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile grid-sizes '6x4'
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile preset-resize-1 "['<Primary><Shift><Alt>o']"
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile preset-resize-2 "['<Primary><Shift><Alt>e']"
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile preset-resize-3 "['<Primary><Shift><Alt>u']"
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile preset-resize-4 "['<Primary><Shift><Alt>less']"
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile preset-resize-5 "['<Primary><Shift><Alt>greater']"
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile preset-resize-6 "['<Primary><Shift><Alt>p']"
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile preset-resize-7 "['<Primary><Shift><Alt>q']"
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile preset-resize-8 "['<Primary><Shift><Alt>j']"
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile preset-resize-9 "['<Primary><Shift><Alt>k']"
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile resize1 '3x2 0:0 0:1'
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile resize2 '3x2 1:0 1:1'
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile resize3 '3x2 2:0 2:1'
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile resize4 '3x2 0:0 0:0'
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile resize5 '3x2 1:0 1:0'
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile resize6 '3x2 2:0 2:0'
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile resize7 '3x2 0:0 1:1'
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile resize8 '3x2 1:1 1:1'
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/gTile@vibou/schemas/ set org.gnome.shell.extensions.gtile resize9 '3x2 1:0 2:1'
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor cpu-graph-width 300
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor cpu-refresh-time 1000
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor cpu-show-text false
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor cpu-style 'graph'
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor icon-display false
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor memory-graph-width 300
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor memory-refresh-time 1000
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor memory-show-text false
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor net-graph-width 300
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor net-refresh-time 1000
        - gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor net-show-text false
        - gsettings set org.gnome.desktop.calendar show-weekdate true
        - gsettings set org.gnome.desktop.interface clock-format '12h'
        - gsettings set org.gnome.desktop.interface clock-show-date true
        - gsettings set org.gnome.desktop.interface clock-show-weekday true
        - gsettings set org.gnome.desktop.interface enable-hot-corners true
        - gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
        - gsettings set org.gnome.desktop.interface icon-theme 'Humanity-Dark'
        - gsettings set org.gnome.desktop.interface show-battery-percentage true
        - gsettings set org.gnome.desktop.peripherals.keyboard delay 150
        - gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 16
        - gsettings set org.gnome.desktop.privacy remember-recent-files false
        - gsettings set org.gnome.desktop.privacy remove-old-trash-files true
        - gsettings set org.gnome.eog.ui disable-close-confirmation true
        - gsettings set org.gnome.gedit.plugins active-plugins "['modelines', 'spell', 'drawspaces', 'codecomment', 'docinfo']"
        - gsettings set org.gnome.gedit.preferences.editor auto-indent true
        - gsettings set org.gnome.gedit.preferences.editor bracket-matching true
        - gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
        - gsettings set org.gnome.gedit.preferences.editor display-right-margin true
        - gsettings set org.gnome.gedit.preferences.editor highlight-current-line true
        - gsettings set org.gnome.gedit.preferences.editor insert-spaces true
        - gsettings set org.gnome.gedit.preferences.editor right-margin-position 120
        - gsettings set org.gnome.gedit.preferences.editor scheme 'oblivion'
        - gsettings set org.gnome.gedit.preferences.editor tabs-size 4
        - gsettings set org.gnome.meld highlight-current-line true
        - gsettings set org.gnome.meld highlight-syntax true
        - gsettings set org.gnome.mutter attach-modal-dialogs false
        - gsettings set org.gnome.mutter dynamic-workspaces false
        - gsettings set org.gnome.mutter workspaces-only-on-primary false
        - gsettings set org.gnome.nautilus.compression default-compression-format 'tar.xz'
        - gsettings set org.gnome.nautilus.preferences confirm-trash false
        - gsettings set org.gnome.online-accounts whitelisted-providers '[]'
        - gsettings set org.gnome.shell.app-switcher current-workspace-only true
        - gsettings set org.gnome.shell.extensions.dash-to-dock autohide true
        - gsettings set org.gnome.shell.extensions.desktop-icons show-home false
        - gsettings set org.gnome.shell.extensions.desktop-icons show-trash false
        - gsettings set org.gnome.system.location enabled false

        # Not sure if these need to be ordered, but let's do it anyway to be safe.
        - gsettings set org.gnome.Terminal.ProfilesList list "['982f2a62-6109-4149-9671-0c552d85ea5b']"
        - gsettings set org.gnome.Terminal.ProfilesList default "'982f2a62-6109-4149-9671-0c552d85ea5b'"
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:982f2a62-6109-4149-9671-0c552d85ea5b/ audible-bell false
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:982f2a62-6109-4149-9671-0c552d85ea5b/ default-size-columns 120
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:982f2a62-6109-4149-9671-0c552d85ea5b/ default-size-rows 40
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:982f2a62-6109-4149-9671-0c552d85ea5b/ scrollback-unlimited true
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:982f2a62-6109-4149-9671-0c552d85ea5b/ visible-name 'srlm'
